# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/xenial64"

    config.vm.provision "shell",
        path: "../scripts/setupRoot.sh",
        privileged: true

    config.vm.provision "shell",
        path: "../scripts/setup.sh",
        privileged: false
end
