# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/xenial64"

    config.vm.provision "shell",
        path: "../setup.sh",
        privileged: false

    config.vm.provision "shell",
        path: "../../scripts/installNvm.sh",
        privileged: false
end
